remote_theme: christianezeani/panthera-jekyll

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Manuel Montalvan
subtitle: Full-Stack Developer

left_side:
background_image: "./assets/images/left-background.jpg"
background_color: "#F00"
close_button_color: "#F00"
text_color: "#F00"

footer:
  copyright_text: "&copy; Manuel Montalvan"

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Blog Posts
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:

  - name: facebook
    link: https://www.facebook.com/manuel.montalvan.92
    icon: fab fa-facebook-square

  - name: instagram
    link: https://www.instagram.com/?hl=es-la
    icon: fab fa-twitter


    
